### ISSUE TITLE
Setts "SS" on any completed level on v1.28.0

### ISSUE THREAD

**Issue by kapertdog** [Aeroluna/CustomJSONData#11]

**Comment by BlackCube4** [comment]
I have this problem as well :c

**Comment by kingpanguan** [comment]
same, it ~doubles your percentage, it also shows all other people on the leaderboard as having doubled percentages

**Comment by Fatalution** [comment]
> same, it ~doubles your percentage, it also shows all other people on the leaderboard as having doubled percentages

1.28 is severely outdated and not supported AFAIK

**Comment by Aeroluna** [comment]
> > same, it ~doubles your percentage, it also shows all other people on the leaderboard as having doubled percentages
> 
> 1.28 is severely outdated and not supported AFAIK

Correct
