### ISSUE TITLE
Local build issues

### ISSUE THREAD

**Issue by JonnyVR1** [Aeroluna/CustomJSONData#18]
0>------- Started building project: CustomJSONData
0>Microsoft.NET.RuntimeIdentifierInference.targets(311,5): Message NETSDK1057 : You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
0>CustomJSONData.csproj: Error NU1101 : Unable to find package BeatSaberModdingTools.Tasks.Luna. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org
0>CustomJSONData.csproj: Error NU1101 : Unable to find package LunaBSMod.Tasks. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org
0>------- Finished building project: CustomJSONData. Succeeded: False. Errors: 2. Warnings: 0

Even adding hintpaths to a local copy of LunaTasks doesn't solve this

    <PackageReference Include="LunaBSMod.Tasks" Version="1.0.0" HintPath="$(LunaTaskDir)" />
    <LunaTaskDir>C:\Users\[Redacted]\RiderProjects\LunaBSMod.Tasks</LunaTaskDir>

**Comment by JonnyVR1** [comment]
Your "solution" to this by creating a custom GitHub nuget does not allow other users to login, even when authenticated via github @Aeroluna

**Comment by Meivyn** [comment]
You need to log in with a GitHub token, not your password. This doesn't violate any guidelines.
